// <auto-generated />
namespace Entity2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class mig31 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mig31));
        
        string IMigrationMetadata.Id
        {
            get { return "202012010838022_mig31"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
