// <auto-generated />
namespace Entity2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class mig181220201438 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mig181220201438));
        
        string IMigrationMetadata.Id
        {
            get { return "202012181331425_mig181220201438"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
