// <auto-generated />
namespace Entity2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class mig30 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mig30));
        
        string IMigrationMetadata.Id
        {
            get { return "202011302152442_mig30"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
