// <auto-generated />
namespace Entity2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class _151220201400 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_151220201400));
        
        string IMigrationMetadata.Id
        {
            get { return "202012151100435_151220201400"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
